server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: /home/almir/Dev/Projects/Java/spring-cloud/config-files
    bus:
      enabled: true

  rabbitmq:
    host: localhost
    port: 32768
    username: guest
    password: guest
