server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mirjahal/spring-cloud-config-server-files
    bus:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
