server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: /home/almir/Pessoal/Projects/Java/spring-cloud/config-files

  rabbitmq:
    host: localhost
    port: 32768
    username: guest
    password: guest